### ISSUE TITLE
Solution not working on 5.17.3 kernel

### ISSUE THREAD

**Issue by wyanlord** [HRex39/rtl8852be_bt#2]
make -C /lib/modules/5.17.3-amd64-desktop/build M=/home/wangyan/Downloads/rtl8852be_bt-5.15 modules
make[1]: 进入目录“/usr/src/linux-headers-5.17.3-amd64-desktop”
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: gcc (Uos 8.3.0.6-1+dde) 8.3.0
  You are using:           gcc (Uos 8.3.0.3-3+rebuild) 8.3.0
  CC [M]  /home/wangyan/Downloads/rtl8852be_bt-5.15/btusb.o
/home/wangyan/Downloads/rtl8852be_bt-5.15/btusb.c: In function ‘btusb_probe’:
/home/wangyan/Downloads/rtl8852be_bt-5.15/btusb.c:3819:6: error: ‘struct hci_dev’ has no member named ‘prevent_wake’
  hdev->prevent_wake = btusb_prevent_wake;
      ^~
make[2]: *** [scripts/Makefile.build:288：/home/wangyan/Downloads/rtl8852be_bt-5.15/btusb.o] 错误 1
make[1]: *** [Makefile:1831：/home/wangyan/Downloads/rtl8852be_bt-5.15] 错误 2
make[1]: 离开目录“/usr/src/linux-headers-5.17.3-amd64-desktop”
make: *** [Makefile:17：all] 错误 2

**Comment by HRex39** [comment]
As you can see， the branch is called 5.15. 

You can download newest 5.17 kernel and change it like the Usage says.

**Comment by HRex39** [comment]
By the way, I have also sent relevant Bluetooth adaptation problems to the uos system but have not received a response, expressing deep regret and concern.
